services:
  api:
    build: .
    container_name: zabbix-smartolt-api
    restart: always
    ports:
      - "${PORT:-3010}:${PORT:-3010}"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./data:/usr/src/app/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
